apiVersion: v1
kind: Service
metadata:
  # resolves to example-aws-anywhere.example-aws-anywhere.svc
  name: example-aws-anywhere
  namespace: aws-test
spec:
  ports:
    - name: https
      port: 9443
      protocol: TCP
  selector:
    # IMPORTANT:
    # this has to match the selector in our Deployment later
    app: example-aws-anywhere